spring:
  profiles:
    active: native
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health
