spring:
  data:
    mongodb:
      host: ms-mongodb
      port: 27017
      database: ms-bootcamp-arcelles

server:
  port: ${PORT:0}

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakerevents
  endpoint:
    health:
      show-details: always

application:
  config:
    jwt:
      secret: 5367566B59467373367639792F423F4528482B4D6251655468576D5A77647437
      expiration: 10

springdoc:
  api-docs:
    path: /auth-docs/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  webjars:
    prefix: