spring:
  data:
    mongodb:
      host: ms-mongodb
      port: 27017
      database: ms-bootcamp-arcelles

server:
  port: ${PORT:0}

application:
  config:
    customer-service-url: http://ms-customer-service/api/v1/customers
    credit-service-url: http://ms-credit-service/api/v1/credits
    accounts:
      checking:
        maintenanceFee: 5
        maxMonthlyMovementsNoFee: 5
        transactionCommissionFeePercentage: 5
      fixedterm:
        maxMonthlyMovements: 1
        availableDayForMovements: 20
        maxMonthlyMovementsNoFee: 5
        transactionCommissionFeePercentage: 5
      savings:
        maxMonthlyMovements: 30
        maxMonthlyMovementsNoFee: 5
        transactionCommissionFeePercentage: 5

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakerevents
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        slidingWindowSize: 3
        failureRateThreshold: 100
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        ignoreExceptions:
          - com.project1.ms_account_service.exception.NotFoundException
          - com.project1.ms_account_service.exception.BadRequestException
      creditService:
        slidingWindowSize: 3
        failureRateThreshold: 100
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        ignoreExceptions:
          - com.project1.ms_account_service.exception.NotFoundException
          - com.project1.ms_account_service.exception.BadRequestException
  timelimiter:
    instances:
      customerService:
        timeoutDuration: 2s
        cancelRunningFuture: true
      creditService:
        timeoutDuration: 2s
        cancelRunningFuture: true

springdoc:
  api-docs:
    path: /account-docs/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  webjars:
    prefix: