spring:
  data:
    mongodb:
      host: ms-mongodb
      port: 27017
      database: ms-bootcamp-arcelles

server:
  port: ${PORT:0}

application:
  config:
    jwt:
      secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    kafka:
      topic-name: bootcoin-transactions
      bootstrap-servers: ms-kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakerevents
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /bootcoin-docs/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  webjars:
    prefix: