spring:
  data:
    mongodb:
      host: ms-mongodb
      port: 27017
      database: ms-bootcamp-arcelles

server:
  port: 9090

application:
  config:
    kafka:
      topic-name: wallet-transactions
      bootstrap-servers: ms-kafka-server:9092

springdoc:
  api-docs:
    path: /yanki-docs/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  webjars:
    prefix: