spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms-bootcamp-arcelles

server:
  port: 9090

springdoc:
  api-docs:
    path: /yanki-docs/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  webjars:
    prefix: