spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms-account-service

server:
  port: 8091

account:
  config:
    checking:
      maintenanceFee: 5
      maxMonthlyMovementsNoFee: 5
      transactionCommissionFeePercentage: 5
    fixedterm:
      maxMonthlyMovements: 1
      availableDayForMovements: 20
      maxMonthlyMovementsNoFee: 5
      transactionCommissionFeePercentage: 5
    savings:
      maxMonthlyMovements: 30
      maxMonthlyMovementsNoFee: 5
      transactionCommissionFeePercentage: 5

application:
  config:
    customer-service-url: http://localhost:8090/api/v1/customers
    credit-service-url: http://localhost:8093/api/v1/credits