spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms-account-service

server:
  port: 8091

account:
  config:
    checking:
      maintenanceFee: 5.0
    fixedterm:
      maxMonthlyMovements: 1
    savings:
      maxMonthlyMovements: 5