spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms-account-service

server:
  port: 8091

account:
  config:
    checking:
      maintenanceFee: 5.0
    fixedterm:
      maxMonthlyMovements: 1
      availableDayForMovements: 20
    savings:
      maxMonthlyMovements: 5

application:
  config:
    customer-service-url: http://localhost:8090/api/v1/customers
    credit-service-url: http://localhost:8093/api/v1/credits