spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms-bootcamp-arcelles

server:
  port: 8091

application:
  config:
    customer-service-url: http://localhost:8090/api/v1/customers
    credit-service-url: http://localhost:8093/api/v1/credits

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakerevents
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        slidingWindowSize: 3
        failureRateThreshold: 100
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        ignoreExceptions:
          - com.project1.ms_account_service.exception.NotFoundException
          - com.project1.ms_account_service.exception.BadRequestException
      creditService:
        slidingWindowSize: 3
        failureRateThreshold: 100
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        ignoreExceptions:
          - com.project1.ms_account_service.exception.NotFoundException
          - com.project1.ms_account_service.exception.BadRequestException
  timelimiter:
    instances:
      customerService:
        timeoutDuration: 2s
        cancelRunningFuture: true
      creditService:
        timeoutDuration: 2s
        cancelRunningFuture: true

account:
  config:
    checking:
      maintenanceFee: 5
      maxMonthlyMovementsNoFee: 5
      transactionCommissionFeePercentage: 5
    fixedterm:
      maxMonthlyMovements: 1
      availableDayForMovements: 20
      maxMonthlyMovementsNoFee: 5
      transactionCommissionFeePercentage: 5
    savings:
      maxMonthlyMovements: 30
      maxMonthlyMovementsNoFee: 5
      transactionCommissionFeePercentage: 5