spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms-bootcamp-arcelles

server:
  port: 8090

customer:
  config:
    personal:
      vip:
        avgDailyMinimumAmount: 100
