spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms-bootcamp-arcelles
  redis:
    host: localhost
    port: 6379

server:
  port: ${PORT:0}

customer:
  config:
    personal:
      vip:
        avgDailyMinimumAmount: 100

springdoc:
  api-docs:
    path: /customer-docs/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  webjars:
    prefix: