spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms-credit-service

server:
  port: 8093

application:
  config:
    customer-service-url: http://localhost:8090/api/v1/customers