spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms-transaction-service

server:
  port: 8092

account:
  service:
    baseUrl: http://localhost:8091/api/v1

credit:
  service:
    baseUrl: http://localhost:8093/api/v1

