spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms-bootcamp-arcelles

server:
  port: ${PORT:0}

application:
  config:
    account-service-url: http://ms-account-service/api/v1/accounts
    credit-service-url: http://ms-credit-service/api/v1/credits
    customer-service-url: http://ms-customer-service/api/v1/customers
    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: wallet-transaction-consumer
      topic-name: wallet-transactions

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakerevents
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        slidingWindowSize: 3
        failureRateThreshold: 100
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        ignoreExceptions:
          - com.project1.ms_transaction_service.exception.NotFoundException
          - com.project1.ms_transaction_service.exception.BadRequestException
      creditService:
        slidingWindowSize: 3
        failureRateThreshold: 100
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        ignoreExceptions:
          - com.project1.ms_transaction_service.exception.NotFoundException
          - com.project1.ms_transaction_service.exception.BadRequestException
      accountService:
        slidingWindowSize: 3
        failureRateThreshold: 100
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        ignoreExceptions:
          - com.project1.ms_transaction_service.exception.NotFoundException
          - com.project1.ms_transaction_service.exception.BadRequestException
  timelimiter:
    instances:
      customerService:
        timeoutDuration: 2s
        cancelRunningFuture: true
      creditService:
        timeoutDuration: 2s
        cancelRunningFuture: true
      accountService:
        timeoutDuration: 2s
        cancelRunningFuture: true

springdoc:
  api-docs:
    path: /transaction-docs/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  webjars:
    prefix: