spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms-bootcamp-arcelles

server:
  port: 8092

application:
  config:
    account-service-url: http://localhost:8091/api/v1/accounts
    credit-service-url: http://localhost:8093/api/v1/credits
    customer-service-url: http://localhost:8090/api/v1/customers