spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms-bootcamp-arcelles

server:
  port: ${PORT:0}

application:
  config:
    kafka:
      topic-name: wallet-transactions
      bootstrap-servers: localhost:9092

springdoc:
  api-docs:
    path: /yanki-docs/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  webjars:
    prefix: